$(document).ready(function() {
	if( /test=true/.test( location.search ) ){
		$('head').append('<link rel="stylesheet" href="https://dmitriyprogramer.github.io/belarusski.kz/style.css">')
		$('#rec258526460').append('<body><div class="calcblock"><div class="calcblock-content"><div class="calcblock-h1">Определи свой размер</div><div class="calcblock-p">Заполнив свои параметры, Вы можете определить свой точный размер.</div><div class="calcblock-table"><div class="calcblock-row"><div class="calcblock-num">1</div><div class="calcblock-val">Обхват груди:</div><div class="calcblock-lab">cм</div><input type="text" class="calcblock-input"></div><div class="calcblock-row"><div class="calcblock-num">2</div><div class="calcblock-val">Обхват под грудью:</div><div class="calcblock-lab">cм</div><input type="text" class="calcblock-input"></div><div class="calcblock-row"><div class="calcblock-num">3</div><div class="calcblock-val">Обхват бедер:</div><div class="calcblock-lab">cм</div><input type="text" class="calcblock-input"></div></div><button class="calcblock-btn">Рассчитать</button><div class="calcblock-result"><div class="calcblock-result-item"><div class="calcblock-result-title">Ваш размер бюстгальтера:</div><div class="calcblock-result-res"><div class="calcblock-result-res-item"><div class="calcblock-result-val">95-D</div></div></div></div><div class="calcblock-result-item"><div class="calcblock-result-title">Ваш размер трусиков:</div><div class="calcblock-result-res"><div class="calcblock-result-res-item"><div class="calcblock-result-lab">CIS</div><div class="calcblock-result-val">106</div></div><div class="calcblock-result-res-item"><div class="calcblock-result-lab">EU</div><div class="calcblock-result-val">44</div></div></div></div></div></div><div class="calcblock-bulits"><div class="calcblock-bulit calcblock-bulit-1">1</div><div class="calcblock-bulit calcblock-bulit-2">2</div><div class="calcblock-bulit calcblock-bulit-3">3</div></div></div>');
	}else{
		$('#rec258526460').css({"display":"none"});
	}
});

