$(document).ready(function() {
	if( /test=true/.test( location.search ) ){
		$('#rec258526460').append('<style> .calcblock{ max-width: 1160px; margin: 0 auto; background-image: url(https://dmitriyprogramer.github.io/belarusski.kz/bg.jpg); background-position: right top; background-size: cover; display: flex; font-family: \'Futura\',Arial,sans-serif; } .calcblock-content{ width: 400px; box-sizing: border-box; padding: 30px; } .calcblock-h1{ text-transform: uppercase; font-size: 24px; margin-bottom: 20px; } .calcblock-p{ font-size: 16px; margin-bottom: 20px; } .calcblock-table{ margin-bottom: 30px; } .calcblock-row{ display: flex; align-items: center; font-size: 16px; margin-bottom: 15px; } .calcblock-num{ width: 24px; height: 24px; background: #282727; color: #fff; border-radius: 50%; margin-right: 10px; display: flex; align-items: center; justify-content: center; font-size: 14px; cursor: pointer; } .calcblock-num.checked{ background: #e30016; } .calcblock-btn{ color: #fff; background-color: #737373; font-weight: 500; font-size: 14px; width: 160px; height: 50px; padding: 0 15px; display: block; margin-left: auto; cursor: pointer; border: none; outline: none; transition: .5s; } .calcblock-btn:hover{ background: #282727 } .calcblock-input{ width: 50px; height: 30px; border: 1px solid #777; padding: 0; text-align: center; box-sizing: border-box; } .calcblock-input:focus{ border: 2px solid #e30016; outline: none; } .calcblock-lab{ padding-right: 5px; margin-left: auto; display: block; } .calcblock-result{ margin-top: 30px; } .calcblock-result-item{ display: flex; } .calcblock-result-title{ color: #e30016; font-size: 16px; margin-bottom: 15px;  font-weight: 700; } .calcblock-result-res-item{ display: flex; align-items: center; margin-bottom: 10px; } .calcblock-result-lab{ font-size: 14px; padding-right: 15px; } .calcblock-result-val{ width: 50px; text-align: center; height: 30px; line-height: 30px; color: #e30016; background: #F9CBAB; margin-left: auto; font-weight: 700; } .calcblock-result-res{ margin-left: auto; } .calcblock-bulits{ height: 520px; position: relative; flex-grow: 1; } .calcblock-bulit{ width: 24px; height: 24px; background: #e30016; color: #fff; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 14px; position: absolute; cursor: pointer; } .calcblock-bulit-1{ top: 135px; right: 300px; } .calcblock-bulit-2{ top: 200px; right: 290px; } .calcblock-bulit-3{ top: 360px; right: 310px; } @media screen and (max-width:768px){ .calcblock{ flex-wrap: wrap; background: none; } .calcblock-content{ width: 100%; } .calcblock-bulits{ width: 100%; background-image: url(https://dmitriyprogramer.github.io/belarusski.kz/bg.jpg); background-position: right top; background-size: cover; order: -1; } } </style>')
		$('#rec258526460').append('<body><div class="calcblock"><div class="calcblock-content"><div class="calcblock-h1">Определи свой размер</div><div class="calcblock-p">Заполнив свои параметры, Вы можете определить свой точный размер.</div><div class="calcblock-table"><div class="calcblock-row"><div class="calcblock-num">1</div><div class="calcblock-val">Обхват груди:</div><div class="calcblock-lab">cм</div><input type="text" class="calcblock-input"></div><div class="calcblock-row"><div class="calcblock-num">2</div><div class="calcblock-val">Обхват под грудью:</div><div class="calcblock-lab">cм</div><input type="text" class="calcblock-input"></div><div class="calcblock-row"><div class="calcblock-num">3</div><div class="calcblock-val">Обхват бедер:</div><div class="calcblock-lab">cм</div><input type="text" class="calcblock-input"></div></div><button class="calcblock-btn">Рассчитать</button><div class="calcblock-result"><div class="calcblock-result-item"><div class="calcblock-result-title">Ваш размер бюстгальтера:</div><div class="calcblock-result-res"><div class="calcblock-result-res-item"><div class="calcblock-result-val">95-D</div></div></div></div><div class="calcblock-result-item"><div class="calcblock-result-title">Ваш размер трусиков:</div><div class="calcblock-result-res"><div class="calcblock-result-res-item"><div class="calcblock-result-lab">CIS</div><div class="calcblock-result-val">106</div></div><div class="calcblock-result-res-item"><div class="calcblock-result-lab">EU</div><div class="calcblock-result-val">44</div></div></div></div></div></div><div class="calcblock-bulits"><div class="calcblock-bulit calcblock-bulit-1">1</div><div class="calcblock-bulit calcblock-bulit-2">2</div><div class="calcblock-bulit calcblock-bulit-3">3</div></div></div>');
	}else{
		$('#rec258526460').css({"display":"none"});
	}
});

